# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedLoan',
            fields=[
                ('loan_officer', models.CharField(max_length=255)),
                ('loan_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('borrower', models.CharField(max_length=255)),
                ('total_loan_ammount', models.IntegerField()),
                ('current_milestone', models.CharField(max_length=255)),
                ('loan_type', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('est_funding_date', models.DateField()),
                ('funds_sent_date', models.DateField()),
                ('funded_milestone_date', models.DateField()),
                ('loan_status', models.CharField(max_length=255)),
            ],
        ),
    ]
