# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20161107_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedsDisclosed',
            fields=[
                ('loan_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('loan_officer', models.CharField(max_length=255)),
                ('borrower', models.CharField(max_length=255)),
                ('sub_prop_street', models.CharField(max_length=255)),
                ('sub_prop_city', models.CharField(max_length=255)),
                ('sub_prop_state', models.CharField(max_length=255)),
                ('sub_prop_zip', models.CharField(max_length=255)),
                ('sub_prop_est_value', models.CharField(max_length=255)),
                ('loan_ammount', models.IntegerField()),
                ('application_date', models.DateField()),
                ('disclosures_due_date', models.DateField()),
            ],
        ),
    ]
