# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_needsdisclosed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedloan',
            old_name='total_loan_ammount',
            new_name='total_loan_amount',
        ),
        migrations.RenameField(
            model_name='needsdisclosed',
            old_name='loan_ammount',
            new_name='loan_amount',
        ),
    ]
